# These are supported funding model platforms

github: [isnur]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: isnur
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: [https://www.buymeacoffee.com/isnur, https://www.paypal.me/isnoer]
